services:
  - type: web
    name: tak-tuto-poznam
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn web_app_v14:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.5
